# Uncapacitated Facility Location Problem

In [37]:
#
import os
import sys
import time
import pandas as pd
import numpy as np
import sklearn

sys.path.append("..")

# Personal modules
from lp.uflp import UFLP
from lp.cflp import CFLP
from lp.telp import TELP

# Linear programming modules
import pulp

# Machine learning modules
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# == Regression
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor

# == Classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# == Clustering
from sklearn.cluster import KMeans
from sklearn_som.som import SOM
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN
from sklearn.cluster import OPTICS

# == Neural Networks
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# == Metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report


## Load the data

In [38]:
# import the data and parameters and check the data

data_path = "data/"
start_time = time.time()
# ====Parameters==== #
parameters = pd.read_csv(os.path.join(data_path, "parametros.csv"))
# 1. food_per_person_per_day in tons per day
food_per_person_per_day = float(
    parameters.loc[parameters["parametro"] == "comida_por_persona_en_toneladas"].values[
        0
    ][1]
)
# 2. transport_cost_per_ton_per_km in COP per ton per km
transport_cost_per_ton_per_km = float(
    parameters.loc[
        parameters["parametro"] == "costo_de_transporte_por_tonelada_por_kilomentro"
    ].values[0][1]
)

print(
    f"parameters: \n    food_per_person_per_day: {food_per_person_per_day} \n    transport_cost_per_ton_per_km: {transport_cost_per_ton_per_km}\n"
)
# ====Parameters==== #

# ====importData==== #
# 1. population, from data/municipios_procesado.csv
population = pd.read_csv(
    os.path.join(data_path, "municipios_procesado.csv"), index_col=3
)
# 2. distance, from data/distance_matrix_final.csv
distance = pd.read_csv(
    os.path.join(data_path, "distance_matrix_final.csv"), index_col=0
)
# 3. warehouses, from data/almacenes.csv
warehouses = pd.read_csv(os.path.join(data_path, "almacenes.csv"))
# ====importData==== #

# ====DataProcessing===== #
# fill the nan values in population with the minimum '2024' from the departamento of Chocó for the columns 22:
population.loc[population.isna().any(axis=1), population.columns[18:]] = (
    population[
        population["2024"]
        == population.loc[population["departamento"] == "Chocó"]["2024"].min()
    ]
    .iloc[0, 18:]
    .values
)
# drop the municipalities with nan values in the first column of the distance matrix
distance = distance.dropna(subset=[distance.columns[0]], axis=0)
distance = distance.dropna(subset=[distance.index[0]], axis=1)
# select only the rows in population dpmp that the index is in distance
population = population.loc[distance.index]
# turn the columns of distance into integers
distance.columns = distance.columns.astype(int)
print(
    f"data information: \n    population: {population.shape} \n    distance: {distance.shape} \n    warehouses: \n {warehouses} \n"
)
# ====DataProcessing===== #

# ====DataInformation==== #
# Memory usage of the data
print(f"population memory usage: {population.memory_usage().sum()/1024**2:.2f} MB")
print(f"distance memory usage: {distance.memory_usage().sum()/1024**2:.2f} MB")
print(f"warehouses memory usage: {warehouses.memory_usage().sum()/1024**2:.2f} MB")
# ====DataInformation==== #

# ====DataChecking==== #
# Test to the data if needed
# ====DataChecking==== #
print(f"Elapsed time: {time.time() - start_time:.2f} s")


parameters: 
    food_per_person_per_day: 0.00087617 
    transport_cost_per_ton_per_km: 3364.0

data information: 
    population: (1117, 71) 
    distance: (1117, 1117) 
    warehouses: 
    Type  capacity_ton        cost
0     1          1074   731159925
1     2          2418  1129212606
2     3          9672  4516850424 

population memory usage: 0.61 MB
distance memory usage: 9.56 MB
warehouses memory usage: 0.00 MB
Elapsed time: 0.31 s


## 1. Demand Forecast

we are using the data from the population dataset that has the colombian census information since 1985 to 2035, the current year is 2024 and the last census was performed in 2018, the data was taken on december 2023 from the DANE web page.

First we need to check the current forecast, then use 4 ML algorithms and Deep Learning to create a new model. The Machine Learning algorithms are:
- Multiple Linear Regression.
- Regression Tree.
- Support Vector Machine.
- Random Forest Regression.

Then, we need the Mean Absolute Error (MAE) to compare the models. The best model will be used to forecast the demand for the next 30 years.

In [39]:
# ## 1. Demand Forecast

data = population.copy().iloc[:, 20:]
data = data.transpose()
# train with a random sample of 80% of the data
train = data.sample(frac=0.8, random_state=0)
test = data.drop(train.index)
# 1.1. Multiple Linear Regression
start_time = time.time()
mean_absolute_errors = []
mean_squared_errors = []
r2_scores = []
# for each column in the data
for i in data.columns:
    model = LinearRegression()
    model.fit(np.array(train.index).reshape(-1, 1), train[i])
    predictions = model.predict(np.array(test.index).reshape(-1, 1))
    mean_absolute_errors.append(mean_absolute_error(test[i], predictions))
    mean_squared_errors.append(mean_squared_error(test[i], predictions))
    r2_scores.append(r2_score(test[i], predictions))
print(f"1.1. Multiple Linear Regression: {time.time()-start_time:.2f} s")
print(f"    Mean Absolute Error: {np.mean(mean_absolute_errors)}")
print(f"    Mean Squared Error: {np.mean(mean_squared_errors)}")
print(f"    R2 Score: {np.mean(r2_scores)}")

# 1.2. Regression Tree
start_time = time.time()

mean_absolute_errors = []
mean_squared_errors = []
r2_scores = []
# for each column in the data
for i in data.columns:
    model = DecisionTreeRegressor()
    model.fit(np.array(train.index).reshape(-1, 1), train[i])
    predictions = model.predict(np.array(test.index).reshape(-1, 1))
    mean_absolute_errors.append(mean_absolute_error(test[i], predictions))
    mean_squared_errors.append(mean_squared_error(test[i], predictions))
    r2_scores.append(r2_score(test[i], predictions))
print(f"1.2. Regression Tree: {time.time()-start_time:.2f} s")
print(f"    Mean Absolute Error: {np.mean(mean_absolute_errors)}")
print(f"    Mean Squared Error: {np.mean(mean_squared_errors)}")
print(f"    R2 Score: {np.mean(r2_scores)}")

# 1.3. Support Vector Machine
start_time = time.time()

mean_absolute_errors = []
mean_squared_errors = []
r2_scores = []
# for each column in the data
for i in data.columns:
    model = svm.SVR()
    model.fit(np.array(train.index).reshape(-1, 1), train[i])
    predictions = model.predict(np.array(test.index).reshape(-1, 1))
    mean_absolute_errors.append(mean_absolute_error(test[i], predictions))
    mean_squared_errors.append(mean_squared_error(test[i], predictions))
    r2_scores.append(r2_score(test[i], predictions))
print(f"1.3. Support Vector Machine: {time.time()-start_time:.2f} s")
print(f"    Mean Absolute Error: {np.mean(mean_absolute_errors)}")
print(f"    Mean Squared Error: {np.mean(mean_squared_errors)}")
print(f"    R2 Score: {np.mean(r2_scores)}")

# 1.4. Random Forest Regression
start_time = time.time()

mean_absolute_errors = []
mean_squared_errors = []
r2_scores = []
# for each column in the data
start_time = time.time()

for i in data.columns:
    model = RandomForestRegressor()
    model.fit(np.array(train.index).reshape(-1, 1), train[i])
    predictions = model.predict(np.array(test.index).reshape(-1, 1))
    mean_absolute_errors.append(mean_absolute_error(test[i], predictions))
    mean_squared_errors.append(mean_squared_error(test[i], predictions))
    r2_scores.append(r2_score(test[i], predictions))
print(f"1.4. Random Forest Regression:  {time.time()-start_time:.2f} s")
print(f"    Mean Absolute Error: {np.mean(mean_absolute_errors)}")
print(f"    Mean Squared Error: {np.mean(mean_squared_errors)}")
print(f"    R2 Score: {np.mean(r2_scores)}")

# # 1.5 Deep Learning
# start_time = time.time()
# # for the deep learning model we are going to use a simple neural network with 3 layers using the Keras library
# # we are going to use the same data as before
# from keras.models import Sequential
# from keras.layers import Dense
# import tensorflow as tf
# mean_absolute_errors = []
# mean_squared_errors = []
# r2_scores = []
# # for each column in the data
# for i in data.columns:
#     model = Sequential()
#     model.add(Dense(12, input_dim=1, activation='relu'))
#     model.add(Dense(8, activation='relu'))
#     model.add(Dense(1, activation='linear'))
#     model.compile(loss='mean_squared_error', optimizer='adam')
#     model.fit(np.array(train.index, dtype=float), train[i], epochs=150, batch_size=10, verbose=0)
#     predictions = model.predict(np.array(test.index, dtype=float))
#     mean_absolute_errors.append(mean_absolute_error(test[i], predictions))
#     mean_squared_errors.append(mean_squared_error(test[i], predictions))
#     r2_scores.append(r2_score(test[i], predictions))
# print(f"1.5. Deep Learning:  {time.time()-start_time:.2f} s")
# print(f'    Mean Absolute Error: {np.mean(mean_absolute_errors)}')
# print(f'    Mean Squared Error: {np.mean(mean_squared_errors)}')
# print(f'    R2 Score: {np.mean(r2_scores)}')


1.1. Multiple Linear Regression: 2.32 s
    Mean Absolute Error: 1983.0903511087888
    Mean Squared Error: 271714255.3285868
    R2 Score: 0.6550556575024784
1.2. Regression Tree: 2.00 s
    Mean Absolute Error: 506.4348254252462
    Mean Squared Error: 12224571.61817368
    R2 Score: 0.9839632368722134
1.3. Support Vector Machine: 2.10 s
    Mean Absolute Error: 8518.465071851242
    Mean Squared Error: 3061127831.2831564
    R2 Score: -0.22744499257749734
1.4. Random Forest Regression:  112.56 s
    Mean Absolute Error: 376.47808773500446
    Mean Squared Error: 11481147.346706387
    R2 Score: 0.9844601204496268


## 2. Set facility types

We have 3 types of facilities:
- Type 1: Small facility.
- Type 2: Medium facility.
- Type 3: Large facility.

for each facility type we have the following information:
- Fixed cost.
- Variable cost.

The proposal is to use a mathematical model to determine the number of facilities of each type to minimize the total cost, in order to satisfy the demand. and be able to train a classifier to predict the type of facility that will be needed for the hole country.

### Model

#### Sets
- $I$: Set of municipalities.
- $J$: Types of facilities.

#### Parameters
- $c_{j}$: Capacity of facility type $j$.
- $f_{j}$: Fixed cost of facility type $j$.

- $p_{i}$: Population of municipality $i$.
- $N$: Food Demand per capita in Tonnes.
- $d_{i}$: Demand of municipality $i$ = $p_{i} * N$.
- $r_{i}$: department aggregation of population of municipality $i$.
- $\lambda_{i}$: Multiplier of demand of municipality based on its department population.$

#### Decision Variables
- $x_{ij}$: Number of facilities of type $j$ in municipality $i$.

#### Objective Function
- Minimize the total cost of the facilities.

$$ \text{Min} \sum_{i \in I} \sum_{j \in J} f_{j} * x_{ij} $$

#### Constraints

- Demand constraint: The demand of municipality $i$ must be satisfied.

$$ \sum_{j \in J} x_{ij} * c_{j} \geq d_{i} * \lambda_{i} \quad \forall i \in I $$

- (optional) General capacity:

$$ \sum_{i \in I} \sum_{j \in J} x_{ij} * c_{j} \leq \sum_{i \in I} d_{i} * \lambda_{i} $$

- Non-negativity:

$$ x_{ij} \geq 0 \quad \forall i \in I, \forall j \in J $$

- Integer:

$$ x_{ij} \in \mathbb{Z} \quad \forall i \in I, \forall j \in J $$



In [40]:
# Optimization of the model
p = population["2024"].sample(frac=0.85, random_state=5)


# ====Parameters==== #
c_j = warehouses["capacity_ton"].values.astype(float)
f_j = warehouses["cost"].values.astype(float)


p_i = p.values.astype(int)
n = food_per_person_per_day * 7
d_i = p_i * n
# Lambda = 2 for the top 32 municipalities, 1 for the rest
lambda_i = np.ones(len(p_i)) * 1.1
lambda_i[np.argsort(p_i)[-32:]] = 1.5
# ====Parameters==== #


# Decision variables: $x_{ij}$
I = range(len(p_i))
J = range(len(c_j))
model = pulp.LpProblem("UFLP", pulp.LpMinimize)
x = pulp.LpVariable.dicts(
    "x", ((i, j) for i in I for j in J), lowBound=0, cat="Integer"
)
y = pulp.LpVariable.dicts("y", ((i, j) for i in I for j in J), cat="Binary")
# Objective function
model += (
    pulp.lpSum(f_j[j] * x[(i, j)] for i in I for j in J),
    "Total cost of the facilities",
)
# Constraints
for i in I:
    model += (
        pulp.lpSum(c_j[j] * x[(i, j)] for j in J) >= d_i[i] * lambda_i[i],
        f"Population demand {i}",
    )
    model += (
        pulp.lpSum(x[(i, j)] for j in J) >= 1,
        f"Facility assignment {i}",
    )
    model += (
        pulp.lpSum(y[(i, j)] for j in J) == 1,
        f"Faacility assignment __ {i}",
    )
    for j in J:
        model += (
            x[(i, j)] <= 100 * y[(i, j)],
            f"Fsacility assignment _ {i} _ {j}",
        )


model += pulp.lpSum(x[(i, j)] * c_j[j] for i in I for j in J) >= pulp.lpSum(
    d_i[i] * lambda_i[i] for i in I
)



# Solve the model
model.solve()
# Results
print(f"Status: {pulp.LpStatus[model.status]}")
print(f"Objective function: {pulp.value(model.objective)}")
df = pd.DataFrame(
    [[pulp.value(x[(i, j)]) for j in J] for i in I],
    columns=[f"Facility {j}" for j in J],
    index=p.index,
)
df["demand"] = d_i
df["satisfied"] = sum(df[f"Facility {j}"] * c_j[j] for j in J)
df["cost"] = sum(df[f"Facility {j}"] * f_j[j] for j in J)
df["comb"] = df.apply(lambda x: tuple(x[: len(J)]), axis=1)

display(df.comb.unique().size, df.comb.unique())
display(df)


Status: Optimal
Objective function: 811097283420.0


11

array([(1.0, 0.0, 0.0), (0.0, 0.0, 1.0), (0.0, 3.0, 0.0),
       (0.0, 31.0, 0.0), (3.0, 0.0, 0.0), (0.0, 1.0, 0.0),
       (0.0, 6.0, 0.0), (0.0, 9.0, 0.0), (0.0, 2.0, 0.0), (0.0, 5.0, 0.0),
       (0.0, 10.0, 0.0)], dtype=object)

Facility 0  Facility 1  Facility 2      demand  satisfied         cost  \
dpmp                                                                            
25781         1.0         0.0         0.0   43.932040     1074.0  731159925.0   
47318         1.0         0.0         0.0  186.166849     1074.0  731159925.0   
27073         1.0         0.0         0.0   72.635369     1074.0  731159925.0   
25258         1.0         0.0         0.0   33.793877     1074.0  731159925.0   
19142         1.0         0.0         0.0  193.514411     1074.0  731159925.0   
...           ...         ...         ...         ...        ...          ...   
50590         1.0         0.0         0.0   84.834284     1074.0  731159925.0   
47960         1.0         0.0         0.0   67.673618     1074.0  731159925.0   
5147          1.0         0.0         0.0  320.054387     1074.0  731159925.0   
17486         1.0         0.0         0.0  132.746764     1074.0  731159925.0   
85250         1.0         0.0         0.0  251.405591     1074.0  731159925.0   

                  comb  
dpmp                    
25781  (1.0, 0.0, 0.0)  
47318  (1.0, 0.0, 0.0)  
27073  (1.0, 0.0, 0.0)  
25258  (1.0, 0.0, 0.0)  
19142  (1.0, 0.0, 0.0)  
...                ...  
50590  (1.0, 0.0, 0.0)  
47960  (1.0, 0.0, 0.0)  
5147   (1.0, 0.0, 0.0)  
17486  (1.0, 0.0, 0.0)  
85250  (1.0, 0.0, 0.0)  

[949 rows x 7 columns]

## 3. Set facility capacity

We have m types of facilities with different capacities, the proposal is to use the data generated in the previous step to determine the capacity of each facility type in order to satisfy the demand.
Machine Learning algorithms will be used to Classify the type of facility that will be needed for each municipality.
- Decision Tree.
- Linear Discriminant Analysis.
- Logistic Regression.
- Support Vector Machine.

and deep learning to create a new model. The best model will be used to determine the capacity of each facility type.

The objective is to predict 'comb' with the information of 'demand', 'lat', 'lon', and 'dp'.


In [45]:
data = pd.merge(df, population, left_index=True, right_index=True)
# drop rows with nan in the 'comb' column
data = data.dropna(subset=["comb"])
# train with a random sample of 80% of the data
# The objective is to predict 'comb' with the information of 'demand', 'lat', 'lon', and 'dp'.
data["comb"] = data["comb"].apply(lambda x: str(x))
data["comb"] = LabelEncoder().fit_transform(data["comb"])
data[["demand", "lat", "lon", "dp"]] = StandardScaler().fit_transform(
    data[["demand", "lat", "lon", "dp"]]
)
train_x, test_x, train_y, test_y = train_test_split(
    data[["demand", "lat", "lon", "dp"]], data["comb"], test_size=0.2, random_state=0
)

# 2.1. Decision Tree
start_time = time.time()
model = DecisionTreeClassifier()
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(f"2.1. Decision Tree: {time.time()-start_time:.2f} s")
print(f"    Accuracy: {accuracy_score(test_y, predictions)}")
print(f"    Confusion Matrix: \n {confusion_matrix(test_y, predictions)}")
print(
    f"    Classification Report: \n {classification_report(test_y, predictions, zero_division=1)}"
)

# 2.2. Linear Discriminant Analysis
start_time = time.time()
model = LinearDiscriminantAnalysis()
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(f"2.2. Linear Discriminant Analysis: {time.time()-start_time:.2f} s")
print(f"    Accuracy: {accuracy_score(test_y, predictions)}")
print(f"    Confusion Matrix: \n {confusion_matrix(test_y, predictions)}")
print(
    f"    Classification Report: \n {classification_report(test_y, predictions, zero_division=1)}"
)

# 2.3. Logistic Regression
start_time = time.time()
model = LogisticRegression(max_iter=1000)
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(f"2.3. Logistic Regression: {time.time()-start_time:.2f} s")
print(f"    Accuracy: {accuracy_score(test_y, predictions)}")
print(f"    Confusion Matrix: \n {confusion_matrix(test_y, predictions)}")
print(
    f"    Classification Report: \n {classification_report(test_y, predictions, zero_division=1)}"
)

# 2.4. Support Vector Machine
start_time = time.time()
model = SVC()
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(f"2.4. Support Vector Machine: {time.time()-start_time:.2f} s")
print(f"    Accuracy: {accuracy_score(test_y, predictions)}")
print(f"    Confusion Matrix: \n {confusion_matrix(test_y, predictions)}")
print(
    f"    Classification Report: \n {classification_report(test_y, predictions, zero_division=1)}"
)

# 2.5. Neural Network
start_time = time.time()
model = MLPClassifier(max_iter=1000, tol=1e-4)
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(f"2.5. Neural Network: {time.time()-start_time:.2f} s")
print(f"    Accuracy: {accuracy_score(test_y, predictions)}")
print(f"    Confusion Matrix: \n {confusion_matrix(test_y, predictions)}")
print(
    f"    Classification Report: \n {classification_report(test_y, predictions, zero_division=1)}"
)


2.1. Decision Tree: 0.00 s
    Accuracy: 1.0
    Confusion Matrix: 
 [[  2   0   0   0   0]
 [  0   1   0   0   0]
 [  0   0   2   0   0]
 [  0   0   0 184   0]
 [  0   0   0   0   1]]
    Classification Report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         2
           9       1.00      1.00      1.00       184
          10       1.00      1.00      1.00         1

    accuracy                           1.00       190
   macro avg       1.00      1.00      1.00       190
weighted avg       1.00      1.00      1.00       190

2.2. Linear Discriminant Analysis: 0.00 s
    Accuracy: 0.9842105263157894
    Confusion Matrix: 
 [[  2   0   0   0   0]
 [  0   1   0   0   0]
 [  0   0   2   0   0]
 [  3   0   0 181   0]
 [  0   0   0   0   1]]
    Classification Report: 
               precision    recall  f1-score   support

## 4. Propose a k parameter for clustering using Linear Programming
